################################# Default configuration ###################
baseURL = "https://thenetsec.github.io"
title = "TheNetSec"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate-css/animate.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/wow/wow.min.js"

############################# Navigation ##################################
[menu]

  [[menu.main]]
  name = "About Me"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3  



############################# Default Parameters ##########################
[params]
#logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# post share
postShare = true

# preloader
#[params.preloader]
#enable = true
#preloader = "images/logo.png"

############################# social icons ##########################

[[params.social_Icon]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/7echsec"

[[params.social_Icon]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://in.linkedin.com/in/pratik-shah-8a589220"

[[params.social_Icon]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/pr4tik"


################################# language ################################
[Languages]

  ################################ English Language ########################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  contentDir = "content/english"
  weight = 1
  home = "Home"

